const C=window.STORE_CONFIG||{},grid=document.querySelector("#grid"),status=document.querySelector("#status"),search=document.querySelector("#search"),filter=document.querySelector("#filter"),modal=document.querySelector("#modal"),details=document.querySelector("#details");let books=[];let client;
const esc=s=>String(s??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[x]));
const price=b=>b.is_free||Number(b.price)===0?"FREE":`${Number(b.price).toLocaleString()} ${esc(b.currency||"ETB")}`;
function copyText(v){navigator.clipboard?.writeText(v).then(()=>alert("Copied"));}
function paymentCards(){return `<div class="payment-grid"><div class="pay-card"><strong>🏦 CBE Bank</strong><span>1000034618821</span><small>Anteneh Benti Negawo</small><button class="btn" onclick="copyText('1000034618821')">Copy account</button></div><div class="pay-card"><strong>📱 CBE Birr</strong><span>1000034618821</span><small>Anteneh Benti Negawo</small><button class="btn" onclick="copyText('1000034618821')">Copy number</button></div><div class="pay-card"><strong>📱 Telebirr</strong><span>0926198917</span><small>Anteneh Benti Negawo</small><button class="btn" onclick="copyText('0926198917')">Copy number</button></div></div>`}
function render(){let q=search.value.toLowerCase(),t=filter.value;let list=books.filter(b=>(!q||`${b.title||""} ${b.description||""}`.toLowerCase().includes(q))&&(t==="all"||b.type===t));status.textContent=list.length?`${list.length} book${list.length===1?"":"s"} available`:"No books match your search.";grid.innerHTML=list.map(b=>`<article class="book"><div class="cover">${b.cover_url?`<img src="${esc(b.cover_url)}" alt="">`:"📖"}</div><div class="body"><div class="badge">${esc(b.type||"Book")}</div><h3 class="title">${esc(b.title||"Untitled")}</h3><p class="desc">${esc(b.description||"A book from Anteneh Book Store.")}</p><div class="bottom"><b>${price(b)}</b><button class="btn" data-id="${esc(b.id)}">View</button></div></div></article>`).join("");grid.querySelectorAll("[data-id]").forEach(x=>x.onclick=()=>openBook(x.dataset.id))}
function openBook(id){let b=books.find(x=>String(x.id)===String(id));if(!b)return;details.innerHTML=`<div class="detail-cover">${b.cover_url?`<img src="${esc(b.cover_url)}" alt="">`:"📖"}</div><div class="badge">${esc(b.type||"Book")}</div><h2>${esc(b.title||"Untitled")}</h2><p>${esc(b.description||"No description available.")}</p><p><b>Language:</b> ${esc(b.language||"—")}</p><p><b>Price:</b> ${price(b)}</p><div class="buy-note"><b>🇪🇹 Local payment</b><br>Pay using CBE, CBE Birr, or Telebirr. After payment, enter the transaction/reference number in your order.</div>${paymentCards()}<button class="btn primary" id="buyNow">Create order</button>`;modal.classList.add("open");document.querySelector("#buyNow").onclick=()=>openCheckout(b)}
function openCheckout(b){details.innerHTML=`<p class="eyebrow">🇪🇹 CHECKOUT</p><h2>${esc(b.title)}</h2><p><b>Total: ${price(b)}</b></p>${paymentCards()}<div class="checkout-form"><label>Name<input id="customerName" required placeholder="Your full name"></label><label>Phone<input id="customerPhone" required placeholder="09XXXXXXXX"></label><label>Email <small>(optional)</small><input id="customerEmail" type="email" placeholder="you@example.com"></label><label>Payment reference<input id="paymentReference" placeholder="Transaction/reference number"></label><button class="btn primary" id="submitOrder">Create purchase order</button><p class="small-note">Your order will remain pending until the payment is reviewed.</p><div id="checkoutMsg"></div></div>`;document.querySelector("#submitOrder").onclick=()=>submitOrder(b)}
async function submitOrder(b){const msg=document.querySelector("#checkoutMsg"),name=document.querySelector("#customerName").value.trim(),phone=document.querySelector("#customerPhone").value.trim(),email=document.querySelector("#customerEmail").value.trim()||null,reference=document.querySelector("#paymentReference").value.trim()||null;if(!name||!phone){msg.textContent="Please enter your name and phone number.";return}msg.textContent="Creating your order…";const {data,error}=await client.rpc("create_store_order",{p_book_id:b.id,p_customer_name:name,p_customer_email:email,p_customer_phone:phone});if(error){console.error(error);msg.textContent="Could not create the order. Please try again.";return}const o=Array.isArray(data)?data[0]:data;if(reference){await client.rpc("submit_store_payment",{p_access_token:o.access_token,p_payment_reference:reference})}sessionStorage.setItem("store_order_token",o.access_token);document.querySelector("#orderToken").value=o.access_token;details.innerHTML=`<p class="eyebrow">✅ ORDER CREATED</p><h2>Keep this order code</h2><div class="order-code">${esc(o.access_token)}</div><p><b>${esc(o.book_title)}</b><br>${Number(o.amount).toLocaleString()} ${esc(o.currency)}</p><p>Your order is now <b>${reference?"payment submitted":"pending"}</b>. Keep this code safe. You can use it under <b>My Order</b> to check your status.</p><div class="buy-note">🇪🇹 Payment: CBE 1000034618821 · CBE Birr 1000034618821 · Telebirr 0926198917<br><small>Account name: Anteneh Benti Negawo</small></div><button class="btn primary" id="goOrder">Check order</button>`;document.querySelector("#goOrder").onclick=()=>{modal.classList.remove("open");document.querySelector("#orderToken").value=o.access_token;document.querySelector("#orders").scrollIntoView({behavior:"smooth"});checkOrder()}}
async function checkOrder(){const token=document.querySelector("#orderToken").value.trim(),out=document.querySelector("#orderStatus");if(!token){out.textContent="Enter your order code.";return}out.textContent="Checking…";const {data,error}=await client.rpc("get_store_order",{p_access_token:token});if(error||!data?.length){out.textContent="Order not found. Check the code and try again.";return}const o=data[0];out.innerHTML=`<div class="order-card"><b>${esc(o.book_title)}</b><span>Amount: ${Number(o.amount).toLocaleString()} ${esc(o.currency)}</span><span>Status: <strong>${esc(o.status.replace("_"," "))}</strong></span>${o.status==="approved"?`<button class="btn primary" onclick="requestAccess('${esc(o.order_id)}','${esc(o.book_id)}','${esc(token)}')">Open my book</button>`:"<small>Keep your payment confirmation. Access will appear here after approval.</small>"}</div>`}
async function requestAccess(orderId,bookId,token){const out=document.querySelector("#orderStatus");out.innerHTML="Access is approved. The secure website reader/download will be connected when the book file is uploaded to the website's private storage."}
document.querySelector("#close").onclick=()=>modal.classList.remove("open");modal.querySelector(".backdrop").onclick=()=>modal.classList.remove("open");search.oninput=render;filter.onchange=render;document.querySelector("#checkOrder").onclick=checkOrder;
const saved=sessionStorage.getItem("store_order_token");if(saved)document.querySelector("#orderToken").value=saved;
async function load(){try{client=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);let {data,error}=await client.from("books").select("id,title,description,language,type,format,price,currency,is_free,cover_url,created_at").eq("is_published",true).order("created_at",{ascending:false});if(error)throw error;books=data||[];render()}catch(e){console.error(e);status.textContent="No published books yet. Your catalogue is connected and ready.";books=[];render()}}load();
