(function(){
const C=window.STORE_CONFIG||{};let sb,session;const ADMIN_EMAIL='antenehbenti1221@gmail.com';
const $=id=>document.getElementById(id);
function setAdminVisibility(admin,isAdmin){if(!admin)return;admin.hidden=!isAdmin;admin.style.display=isAdmin?'block':'none';admin.setAttribute('aria-hidden',isAdmin?'false':'true')}
function openAuth(mode='signin'){const m=$('authModal'),c=$('authContent');if(!m||!c)return;const signup=mode==='signup';c.innerHTML=`<p class="eyebrow">🇪🇹 ${signup?'CREATE ACCOUNT':'WELCOME BACK'}</p><h2>${signup?'Create your customer account':'Sign in to Anteneh Book Store'}</h2><p class="small-note">${signup?'Use your email or phone number and password.':'Sign in to buy books and access your approved purchases.'}</p><label>${signup?'Email / Phone':'Email / Phone number'}<input id="authEmail" type="text" autocomplete="username" inputmode="email" required placeholder="Email / Phone"></label><label>Password<div class="password-wrap"><input id="authPassword" type="password" autocomplete="current-password" required><button type="button" class="password-toggle" id="passwordToggle" aria-label="Show password">Show</button></div></label><button type="button" class="btn primary" id="authSubmit">${signup?'Create account':'Sign in'}</button><p id="authMsg" class="small-note"></p><button type="button" class="text-button" id="authSwitch">${signup?'Already have an account? Sign in':'New customer? Create an account'}</button>`;m.classList.add('open');$('authSubmit').onclick=()=>submitAuth(signup);$('authSwitch').onclick=()=>openAuth(signup?'signin':'signup');const pw=$('authPassword'),toggle=$('passwordToggle');toggle.onclick=e=>{e.preventDefault();e.stopPropagation();const visible=pw.type==='text';pw.type=visible?'password':'text';toggle.textContent=visible?'Show':'Hide';toggle.setAttribute('aria-label',visible?'Show password':'Hide password')};setTimeout(()=>$('authEmail')?.focus(),50)}
async function submitAuth(signup){const msg=$('authMsg'),identifier=$('authEmail').value.trim(),password=$('authPassword').value;if(!identifier||!password){msg.textContent='Please enter your email or phone number and password.';return}$('authSubmit').disabled=true;msg.textContent=signup?'Creating account…':'Signing in…';let result;try{if(signup){const isPhone=/^\+?[0-9][0-9\s-]{6,}$/.test(identifier);result=isPhone?await sb.auth.signUp({phone:identifier.replace(/[\s-]/g,''),password}):await sb.auth.signUp({email:identifier,password})}else{const isPhone=/^\+?[0-9][0-9\s-]{6,}$/.test(identifier);result=await sb.auth.signInWithPassword(isPhone?{phone:identifier.replace(/[\s-]/g,''),password}:{email:identifier,password})}}catch(e){result={error:e}}$('authSubmit').disabled=false;if(result.error){msg.textContent=result.error.message;return}session=result.data.session||null;if(signup&&!session){msg.textContent='Account created. If confirmation is required, check your email or phone, then sign in.';return}$('authModal').classList.remove('open');window.location.hash='home';await updateAuthUI()}
async function updateAuthUI(){if(!sb)return;const r=await sb.auth.getSession();session=r.data.session||null;const btn=$('authBtn'),admin=$('adminLink');if(!btn)return;setAdminVisibility(admin,false);if(!session){btn.textContent='Sign in';btn.title='Sign in or create an account';btn.setAttribute('aria-label','Sign in or create an account');btn.onclick=e=>{e.preventDefault();e.stopPropagation();openAuth('signin')};return}btn.textContent='Sign out';btn.title='Sign out';btn.setAttribute('aria-label','Sign out');btn.onclick=async e=>{e.preventDefault();e.stopPropagation();await sb.auth.signOut();session=null;await updateAuthUI()};const email=(session.user.email||'').trim().toLowerCase();let isAdmin=email===ADMIN_EMAIL.toLowerCase();try{const {data}=await sb.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(data?.user_id===session.user.id)isAdmin=true}catch(e){}setAdminVisibility(admin,isAdmin);setTimeout(()=>window.startOrderPolling?.(),150)}
function installNavFix(){if(document.getElementById('auth-nav-fix'))return;const s=document.createElement('style');s.id='auth-nav-fix';s.textContent='.nav{min-width:0}.brand{min-width:0}.brand>span:last-child{min-width:0}.nav-actions{flex:0 0 auto;min-width:0}.auth-button{flex:0 0 auto;width:96px!important;max-width:96px!important;min-width:96px!important;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding-left:8px!important;padding-right:8px!important;font-size:12px!important}.auth-button::after{content:""}@media(max-width:520px){.nav-actions{gap:4px}.language-select{flex:0 0 68px;width:68px;max-width:68px}.auth-button{width:78px!important;max-width:78px!important;min-width:78px!important;font-size:11px!important}.menu{flex:0 0 38px;width:38px}}';document.head.appendChild(s)}
function requireAuth(next){if(session)return next();openAuth('signin')}
function prepareCheckoutFields(){const meta=session?.user?.user_metadata||{},name=meta.full_name||session?.user?.email||'',phone=meta.phone||'',email=session?.user?.email||'';const n=$('customerName'),p=$('customerPhone'),e=$('customerEmail');if(n){n.value=name;n.closest('label').hidden=true}if(p){p.value=phone;p.closest('label').hidden=!phone}if(e){e.value=email;e.closest('label').hidden=true}}
document.addEventListener('DOMContentLoaded',()=>{installNavFix();sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);$('authClose')?.addEventListener('click',()=>$('authModal').classList.remove('open'));$('authModal')?.querySelector('.backdrop')?.addEventListener('click',()=>$('authModal').classList.remove('open'));sb.auth.onAuthStateChange(()=>setTimeout(updateAuthUI,100));updateAuthUI();window.STORE_AUTH={get session(){return session},requireAuth,prepareCheckoutFields}});
window.openStoreAuth=openAuth;
const oldOpenCheckout=window.openCheckout;Object.defineProperty(window,'openCheckout',{configurable:true,writable:true,value:function(book){if(window.STORE_AUTH?.session){oldOpenCheckout(book);setTimeout(prepareCheckoutFields,50)}else requireAuth(()=>{oldOpenCheckout(book);setTimeout(prepareCheckoutFields,50)})}});
})();