(function(){
const C=window.STORE_CONFIG||{};let sb,session;
const $=id=>document.getElementById(id);
function openAuth(mode='signin'){const m=$('authModal'),c=$('authContent');if(!m||!c)return;const signup=mode==='signup';c.innerHTML=`<p class="eyebrow">🇪🇹 ${signup?'CREATE ACCOUNT':'WELCOME BACK'}</p><h2>${signup?'Create your customer account':'Sign in to Anteneh Book Store'}</h2><p class="small-note">${signup?'Your account keeps your purchases and profile together.':'Sign in to buy books and access your approved purchases.'}</p>${signup?'<label>Full name<input id="authName" autocomplete="name" required></label><label>Phone<input id="authPhone" autocomplete="tel" required placeholder="09XXXXXXXX"></label>':''}<label>Email<input id="authEmail" type="email" autocomplete="email" required></label><label>Password<input id="authPassword" type="password" autocomplete="current-password" required></label><button class="btn primary" id="authSubmit">${signup?'Create account':'Sign in'}</button><p id="authMsg" class="small-note"></p><button class="text-button" id="authSwitch">${signup?'Already have an account? Sign in':'New customer? Create an account'}</button>`;m.classList.add('open');$('authSubmit').onclick=()=>submitAuth(signup);$('authSwitch').onclick=()=>openAuth(signup?'signin':'signup')}
async function submitAuth(signup){const msg=$('authMsg'),email=$('authEmail').value.trim(),password=$('authPassword').value;if(!email||!password){msg.textContent='Please enter your email and password.';return}$('authSubmit').disabled=true;msg.textContent=signup?'Creating account…':'Signing in…';let result;if(signup){const name=$('authName').value.trim(),phone=$('authPhone').value.trim();if(!name||!phone){msg.textContent='Please enter your name and phone.';$('authSubmit').disabled=false;return}result=await sb.auth.signUp({email,password,options:{data:{full_name:name,phone}}})}else result=await sb.auth.signInWithPassword({email,password});$('authSubmit').disabled=false;if(result.error){msg.textContent=result.error.message;return}session=result.data.session;if(!session&&signup){msg.textContent='Account created. Check your email if confirmation is required, then sign in.';return}$('authModal').classList.remove('open');await updateAuthUI()}
async function updateAuthUI(){if(!sb)return;const r=await sb.auth.getSession();session=r.data.session||null;const btn=$('authBtn'),admin=$('adminLink');if(!btn)return;if(!session){btn.textContent='Sign in';btn.onclick=()=>openAuth('signin');if(admin)admin.hidden=true;return}const email=session.user.email||'';btn.textContent=`${email} · Sign out`;btn.onclick=async()=>{await sb.auth.signOut();session=null;updateAuthUI();};if(admin){const {data}=await sb.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();admin.hidden=!data}}
function requireAuth(next){if(session)return next();openAuth('signin')}
function prepareCheckoutFields(){const meta=session?.user?.user_metadata||{},name=meta.full_name||session?.user?.email||'',phone=meta.phone||'',email=session?.user?.email||'';const n=$('customerName'),p=$('customerPhone'),e=$('customerEmail');if(n){n.value=name;n.closest('label').hidden=true}if(p){p.value=phone;p.closest('label').hidden=!phone}if(e){e.value=email;e.closest('label').hidden=true}}
document.addEventListener('DOMContentLoaded',()=>{sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);$('authClose')?.addEventListener('click',()=>$('authModal').classList.remove('open'));$('authModal')?.querySelector('.backdrop')?.addEventListener('click',()=>$('authModal').classList.remove('open'));sb.auth.onAuthStateChange(()=>setTimeout(updateAuthUI,100));updateAuthUI();window.STORE_AUTH={get session(){return session},requireAuth,prepareCheckoutFields}});
window.openStoreAuth=openAuth;
const oldOpenCheckout=window.openCheckout;Object.defineProperty(window,'openCheckout',{configurable:true,writable:true,value:function(book){if(window.STORE_AUTH?.session){oldOpenCheckout(book);setTimeout(prepareCheckoutFields,50)}else requireAuth(()=>{oldOpenCheckout(book);setTimeout(prepareCheckoutFields,50)})}});
})();